### ISSUE TITLE
Update to adept to Google's behavior

### ISSUE THREAD

**Issue by csillag** [prerender/prerender-node#105]
Ad the README file saya, Prerender adheres to google's `_escaped_fragment_` proposal.

However, as far as I can tell, Google has already deprecated that proposal, and stopped
adhering to it.

In practice, this means that simply having ` <meta name="fragment" content="!">` in the header is no longer sufficient for making GoogleBot add the required query to the URL... which means that currently, GoogleBot is _not_ getting the prerendered version.

To solve this, we would need to add the user agent string of the google bot back to the allowed list.

(Or am I missing something here?)

**Comment by csillag** [comment]
> However, as far as I can tell, Google has already deprecated that proposal, and stopped
adhering to it.

Update: I have learnt that while it's true that the proposal is now considered deprecated, Google still honors this meta tag. It's only the search console's "fetch as google" tool that doesn't - but that is not a real problem.

So the point is moot, and I am closing this issue.

**Comment by thoop** [comment]
Thanks! Yeah, you are correct that Google still supports that meta tag and the `_escaped_fragment_` crawling protocol. Only "Fetch as Google" has an issue where they don't automatically check for it.
