### ISSUE TITLE
504 when accessing Angularjs routes

### ISSUE THREAD

**Issue by UiCandy** [prerender/prerender-node#107]
I've setup an express wrapper for my angularjs app with the prerender-node package. 
I cannot access any nested urls, it's constantly returning a 504, without the ?_escaped_fragment bit the app runs as expected.

I've also included #!'s in my urls so that it's easier to debug. Has anyone faced this issue? I've been trying to resolve it since the past week.
Page Url: http://localhost:8080/#!/1/1877
While using Prerender: http://localhost:8080/?escaped_fragment=/1/1877/ - > 504 error

Thanks!

**Comment by UiCandy** [comment]
Takes 5 minutes to add your own phantomjs server and prerender pages yourself instead of using this.
Thanks to prerender.io for not making me lazy and saving money eventually. haha

**Comment by thoop** [comment]
Sorry for the delay! Not sure if you fixed this but if you were using our hosted service, we wouldn't be able to access your localhost URLs. In that case, you can download and start our open source prerender server and point your middleware at that in your dev environment.
