### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by longuniquename** [prerender/prerender-node#110]
Hi,
I'm using `dfischer:prerenderio` package in my meteor app. And when I try to access `http://localhost:3000/?_escaped_fragment_=` it causes an error:
```
Error: socket hang up
 at createHangUpError (http.js:1528:15)
 at Socket.socketOnEnd (http.js:1624:23)
 at Socket.g (events.js:180:16)
 at Socket.emit (events.js:117:20)
 at _stream_readable.js:944:16
 at process._tickCallback (node.js:458:13)
```
What am I doing wrong?
Thanks in advance,
Dmytro

**Comment by thoop** [comment]
Sorry for the delay! Are you using our hosted prerender service? If so, we won't be able to access your localhost URL so that might be causing issues. If you are using the prerender server running locally on your machine, are you seeing a request get sent to that prerender server?
