### ISSUE TITLE
Waiting until all assets are loaded before taking HTML snapshot

### ISSUE THREAD

**Issue by declanelcocks** [prerender/prerender-node#111]
I'm using the self-hosted solution to host a `prerender` server and use `prerender-node` to access that server. I'm in the early stages of setting this up and was wanting to know the correct/suggested approach for waiting until everything is ready to render the HTML.

For the JS (Angular), I assume you would use `window.prerenderReady = true` at some point in your JS code to notify prerender that it's ready, but what about the CSS or images? Currently when I try to ping my website using my `prerender` server, it's 50/50 whether the correct page will be rendered. Sometimes the page will render like normal, and sometimes it will render with a lot of `404`s for the CSS/images on the page.

Obviously that will be terrible for SEO, so what is the recommended approach for handling assets? I would be against doing some kind of `timeOut` to check if it's loaded as this could affect the time it takes for the `googlebot` to fetch the page.

**Comment by maxfriedmann** [comment]
@declanelcocks what was your final solution? Am facing the same problem...

**Comment by thoop** [comment]
@maxfriedmann if you are running into timing issues, feel free to send us an email at support@prerender.io with the URL you are using. Different issues can cause a page to not render fully.

**Comment by maxfriedmann** [comment]
Actually, not having some images loaded is not a problem for a search bot. 

We managed to use window.prerenderReady=false/true after all js/css files have been loaded.
