### ISSUE TITLE
[METEOR] Name is not a string. perhaps the file extension isn't .rjs?

### ISSUE THREAD

**Issue by Grep-Juub** [prerender/prerender-node#112]
Hello guys !

Thanks for this awesome package, I was able to test it with  a local prerender server, but when I try to use it in my meteor app, it throw me the error I put on title, I've simply do that: 

`this.prerenderio = Npm.require('prerender-node');`

Any idea of why I've this issue ?
Thanks

**Comment by thoop** [comment]
Hmm, I'm not sure what would cause that. We definitely don't have any .rjs files. Does Meteor require them to be .rjs?

**Comment by Grep-Juub** [comment]
Hey, sorry but finally I found the solution ! The answer was `mrt:require` an old package still in my meteor instance which I just remove because since Meteor@1.3 we have native 'import/require' support.
Thanks for your time :)

**Comment by thoop** [comment]
Awesome!
