### ISSUE TITLE
Bing doesn't append `?_escaped_fragment_`

### ISSUE THREAD

**Issue by VanTudor** [prerender/prerender-node#113]
I know there have been some talks over _fetch As Googlebot_'s bug and it appears that Bing is doing the same now.

I'm currently trying to fetch http://mywebsite.com/home as Bingbot, but `prerender.shouldShowPrerenderedPage(req)` returns false as Bing doesn't seem to append `_escaped_fragment_` to the url.

**Notes:**
 `console.log(req.originalUrl);` returns /home
 `console.log(req.headers['user-agent']);` returns `Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)`

I have 
`<meta name="fragment" content="!">` in the `<head>`
I use Angular 1.5 with `$locationProvider.html5Mode(true);`
And `app.use( require( 'prerender-node').set( 'prerenderToken', 'myToken'));` is the first thing I do in my node app after including my module dependecies.

**Comment by thoop** [comment]
"Fetch as Bing" does have the same bug actually. The real bingbot does automatically check for the fragment meta tag and re-request the URL with the `?_escaped_fragment_=` query parameter but Fetch as Bingbot doesn't check for the fragment meta tag. If you enter your URL with the `?_escaped_fragment_=` query parameter, it should show the correct prerendered page.

Sorry for any confusion there!
