### ISSUE TITLE
When forwardHeaders set to true, the "host" header cause infinite loop.

### ISSUE THREAD

**Issue by sunshineo** [prerender/prerender-node#115]
Say value for the host header is: "www.mydomain.com"

Your code use this value to build out the url. https://github.com/prerender/prerender-node/blob/master/index.js#L241

You build a url like this: https://api.prerender.io/https://www.mydomain.com/path?_escaped_fragment_=
But you put this url as an uri inside the option. https://github.com/prerender/prerender-node/blob/master/index.js#L167
And then you call request.get without the url but just the option https://github.com/prerender/prerender-node/blob/master/index.js#L182

I don't know why you do this. Maybe you feel it's fancy. But the request package is also doing something fancy. They call https with the options here https://github.com/request/request/blob/master/request.js#L740

So what actually get called is:
https://www.mydomain.com/https://www.mydomain.com/url?_escaped_fragment_=
and then it got redirected
https://www.mydomain.com/https://www.mydomain.com/https://www.mydomain.com/url?_escaped_fragment_=
and then
https://www.mydomain.com/https://www.mydomain.com/https://www.mydomain.com/https://www.mydomain.com/url?_escaped_fragment_=

you get the idea. This just recursively goes until it is too deep and return a 400

**Comment by sunshineo** [comment]
I think I'm wrong somewhere. I need to experiment more.

**Comment by thoop** [comment]
So you have the `forwardHeaders` option set to `true`?

Can you provide a test case showing this looping issue? I'm not able to reproduce it locally. Assuming your are on the latest version of prerender-node, which version of request are you using?

**Comment by sunshineo** [comment]
It's probably because it need to be https. I'm trying to create an repro

**Comment by sunshineo** [comment]
I'm trying to create an repro

**Comment by sunshineo** [comment]
This is happening to me when I deployed to docker cloud, with a haproxy serving https.
However, I have not been able to reproduce this locally yet. I'm still trying.

**Comment by sunshineo** [comment]
I have a repo now. The root cause seems to be that haproxy is using the 'host' header to decide where to route the traffic
One thing I did not describe properly is that I am hosting my own prerender server using https://github.com/prerender/prerender

So I have a haproxy routing the traffic. The request for prerender is like this:
url: https://prerender.mydomain.com/https://www.mydomain.com/path?_escaped_fragment_=
headers: host: www.mydomain.com

Haproxy routed this request back to the service serving https://www.mydomain.com instead of the service serving https://prerender.mydomain.com

I would suggest my pull request get merged. It is definitely a good idea to remove the 'host' header since we can't expect what is using it how.

I'll post repro steps in details soon.

**Comment by sunshineo** [comment]
Repro is here https://github.com/sunshineo/prerender-node-repro
