### ISSUE TITLE
Always send a GET request. Even when user is doing HEAD

### ISSUE THREAD

**Issue by sunshineo** [prerender/prerender-node#120]
As we can see from this line
https://github.com/prerender/prerender-node/blob/master/index.js#L188 , it will always do a GET. Search in that file for "req.method" and you will see it is not being used to decide what type of calls to make at all.

When user use a HEAD instead of a GET, we need to respect and keep the method. The method type is being used by the prerender server to perform different logic. The problem I faced was that HEAD was supposed to clear out the S3 cache. Have a look at line: https://github.com/prerender/prerender/blob/master/lib/plugins/s3HtmlCache.js#L12
But I cannot achieve this because even though I sent a HEAD request, this library changed it to a GET before sending to prerender server.

**Comment by thoop** [comment]
I wouldn't recommend sending HEAD requests through your website all the way to the prerender server to update the cache. Can you send a HEAD request to your prerender server directly?

**Comment by sunshineo** [comment]
@thoop What is the downside for send HEAD request through website to prerender? All the GET requests are going through.

**Comment by thoop** [comment]
That's just a weird way to bypass your cache. Crawlers are never sending a HEAD request to your pages to get the prerendered page so the only use case there is so that you can cause a cache refresh. If you are the one making the request, then why not make the request directly to your prerender server?

**Comment by sunshineo** [comment]
@thoop There are a lot of reasons that we don't want to directly hit the prerender server, such as centralize logging, re-use the login and authorization system in the main server. And lastly in my case, it is actually not "me" making the request, but the end user client. They upload something and would like to trigger a cache refresh. They can't hit the prerender server directly from their browser Javascript. It will cause a CORS because my prerender server is on prerender.mydomain.com, not www.mydomain.com

So my user client send a HEAD request, I check they are indeed login, then I let prerender-node handle it. But it changed the HEAD to GET.

Also HEAD is absolutely NOT a weird way to bypass cache. My client is on mobile and they really don't need to GET the large prerendered html. They just want to trigger it, so HEAD is perfect.

**Comment by thoop** [comment]
I would suggest that you have the user send a request to your server and your server then send the correct request to bypass the cache.

Sorry, but we won't be introducing this change in order to handle your use case. Feel free to fork the middleware if you want to add in custom functionality.

**Comment by sunshineo** [comment]
@thoop Let's not jump to conclusions based on feelings. Let's layout the pros and cons and have a constructive discussion. This is not just about my use cases. I believe my suggestions will improve the quality and flexibility of this middleware over all.
1. The server side code does leverage the HTTP methods for different logic. So why not align this middle ware with the server side?
2. Keep the original HTTP methods feels much more intuitive than allow "GET" and "HEAD", reject everything else, but also change "HEAD" to "GET".
3. I would think there are more people have similar use cases like me. They may not have speak up, or they may found a workaround such as hit the prerender server directly, but wouldn't it be nice if this middleware supports it and no one need to do any customization?

**Comment by thoop** [comment]
We only allow GET requests for our hosted service. The S3HtmlCache plugin is the only one that has that cache bypass and we don't use that with our hosted service so I'm hesitant to make a change just for that basic plugin. Making that change to allow other HTTP methods also adds a lot of complexity that needs to be added to all other middleware frameworks that we provide.

Sending another HTTP method is confusing there. If you send an HTTP HEAD request to the Prerender server, I would think that would make an HTTP HEAD request to the URL you pass in, not bypass the cache and then make a GET request.

Also, according to the [rfc spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html):
`In particular, the convention has been established that the GET and HEAD methods SHOULD NOT have the significance of taking an action other than retrieval.`

So it's already not a good thing that sending a HEAD request overrides the cache.

Please feel free to fork this library if you'd like to add that in for yourself.

**Comment by sunshineo** [comment]
@thoop You have several good points. If your hosted service does not allow HEAD, I would recommend simply reject HEAD in this plugin instead of change it to GET. I agree with the rfc point that GET and HEAD should not cause any significant change. But if you think about the very first request, even it is a GET, it miss the cache and cause a render. Let me think about this a little more.
