### ISSUE TITLE
Xing is missing

### ISSUE THREAD

**Issue by helgetan** [prerender/prerender-node#124]
Hi,

what about Xing.de/com/net ? We are using xing to share content, but angular is not rendered.

best
AH

**Comment by thoop** [comment]
Does xing have their own crawler they use when you share a URL in the chat section? Are you able to see which crawler user agent they are using?

**Comment by thoop** [comment]
Any more info here? Feel free to reopen with the user agent you'd like us to add.

**Comment by helgetan** [comment]
The Xing Useragent is "XING-contenttabreceiver/2.0" as stated in 
https://gist.github.com/Paratron/8676518
