### ISSUE TITLE
Google no longer appends ?_escaped_fragment_

### ISSUE THREAD

**Issue by GeKorm** [prerender/prerender-node#128]
I am no longer seeing any `?_escaped_fragment_` hits from Googlebot in my nginx access logs. Bing is using the fragment url.  

I'm wondering if Google has finally stopped this practice and if there's a way to test this more reliably. 
Thank you.

**Comment by thoop** [comment]
Google still crawls using the `?_escaped_fragment_=` parameter. You might have a misconfiguration somewhere. Do you still have the `<meta name="fragment " content="!">` tag in your `<head>`? Feel free to send us your URL at support@prerender.io and we'll take a look at things.
