### ISSUE TITLE
No async fetched data in React component

### ISSUE THREAD

**Issue by programmersharp** [prerender/prerender-node#129]
I am using https://github.com/mzabriskie/axios to get data from the remote service asynchronously in componentDidMount. It works fine at the normal web page . But when I try with ?_escaped_fragment_= it doesn't show me dynamically fetched content. I am using React and local prerender server. I can share the source code if needed.

**Comment by thoop** [comment]
Sounds like a javascript error might be preventing the page from rendering fully. Can you share a URL of your website? Feel free to send it to support@prerender.io if you want to keep it private.

**Comment by programmersharp** [comment]
There are no any errors in Chrome console while rendering the page. Still we don't have the public URL of this site, so is it possible if I send some very simple part of the source code  to this email?

**Comment by thoop** [comment]
Sorry, that won't help since we need to execute the page in our rendering engine. Are you able to put it on a public IP address for a short period of time? Feel free to email us the IP address at support@prerender.io

**Comment by programmersharp** [comment]
Is it okay if I put just html page with necessary js files? So, it will be without nodejs.

**Comment by programmersharp** [comment]
I guess I know where is the problem. I tried with different approaches for taking async data (fetch native, Axios, whatwg-fetch), nothing helped except jquery. So I guess there is no support of these libraries in PhantomJS, though it sounds strange a little bit. Actually I don't want to include jquery only for fetching data, because it has unnecessary code for DOM manipulations. So, ideally I would prefer lightweight plugin for making web requests from the browser. But for now I don't see other solutions.

**Comment by thoop** [comment]
PhantomJS shouldn't have any problems with those different libraries unless they are using ES6 directly. If you can make your site public for a short period of time and send us an email, we might be able to help figure out why PhantomJS was having problems.

**Comment by programmersharp** [comment]
http://social.elinext.com/express/myapp

Local prerender service is running on those machine too on port 3001.

**Comment by thoop** [comment]
I haven't been able to figure out what's going on here. We aren't seeing any errors at all when testing that page with our current version of Prerender. It's just loading your vendor.js and main.js but no other ajax requests are being sent. Your page even works in older versions of Safari, so the version of webkit that PhantomJS uses should support it.

Are you able to add any console output to your code to diagnose how far it's getting?

**Comment by programmersharp** [comment]
I am not sure about what logs are you interested.. Where should I add logs? If I add logs in React component how I can see logs in prerenderer service? But I am not sure how it could help as there are no errors. Obviously the ajax request should go.

**Comment by thoop** [comment]
Yeah this seems to be a weird case where PhantomJS is having trouble with the page. If you add `console.log('prerender test');` in different places in your code (and change the message so we know where that ended up) then we might be able to see how far it's getting.

If you enable the `logger()` plugin in the `server.js` file then you should see any console output on the Prerender server console.

Sorry for the trouble here! Let me know if you put those console logs in and I can test too.

**Comment by programmersharp** [comment]
I've added some log, but it didn't help me. I see in the Prerender server console only the single message, that is shown exactly before calling axios:

![image](https://cloud.githubusercontent.com/assets/2078015/23293376/e51a78ec-fa76-11e6-956b-558dd5f7851f.png)

The source code for this method is:

![image](https://cloud.githubusercontent.com/assets/2078015/23293531/a6afdec0-fa77-11e6-8d17-60c16c9b1681.png)

The source code was also uploaded to http://social.elinext.com/express/myapp, so you can check it too.

**Comment by thoop** [comment]
Does axios use the global Promise introduced in ES6? Or does it use a polyfill for browsers that don't support it? It definitely looks like phantomjs is having trouble inside the `axios_1.default.get` function.

**Comment by programmersharp** [comment]
I don't know much about axios, but I can see 'axios depends on a native ES6 Promise implementation to be supported. If your environment doesn't support ES6 Promises, you can polyfill.' under https://github.com/mzabriskie/axios.

**Comment by thoop** [comment]
Can you try including a Promise polyfill? I can re-test once you add that. Sorry for the trouble here!

**Comment by programmersharp** [comment]
Yeah, including a Promise polyfill solved the issue with axios library. I am going to close the issue, thank you very much with your excellent help!

**Comment by thoop** [comment]
Great! Sorry about that. Usually we see an error on the console if it's a Promise issue. Glad that fixed it.
