### ISSUE TITLE
Bing search results are not pulling cached html

### ISSUE THREAD

**Issue by wlingke** [prerender/prerender-node#130]
In Bing only, some of our pages look like this:

![image](https://cloud.githubusercontent.com/assets/3145536/23075866/e8db2e74-f4f2-11e6-99c3-3056b8c019c9.png)

While others seem okay:

![image](https://cloud.githubusercontent.com/assets/3145536/23075878/f4e835ae-f4f2-11e6-9922-506f491c278c.png)

This is not a problem on Google. Also when I append the escape fragment on any page, the correct cached prerender page is served. 

When I visit my prerender.io dashboard, I can see that "Bingbot 2.0" has showed up on the crawl stats page. For instance, the page above with the issue was crawled just yesterday:
![image](https://cloud.githubusercontent.com/assets/3145536/23076001/7c0ec5a2-f4f3-11e6-9010-579e178ce381.png)

Finally, when I click on "Raw HTML" on the Cached Pages dashboard, it shows up correctly (https://prerender.io/raw-html?url=https%3A%2F%2Fwww.ovidlife.com%2Fwhat-is-life-settlement&adaptiveType=desktop)

What could be the reason for this?

**Comment by thoop** [comment]
Looks like Bing just isn't updating their index fast enough after crawling the page. Keep an eye on that page in Bing and see if they update it with the correct page. Since they crawled the page through Prerender, I'd expect them to index it correctly.

You might want to send Bing a support email through Bing Webmaster Tools just to make sure, but it looks like Prerender is working correctly .

**Comment by wlingke** [comment]
Hmm we've been using Prerender for a over year now though this is the first time I've checked my Bing search results. They've had a lot of time to update their records.

In any case, I've sent them a support message as you suggested. Will let you know if there's any actionable things for Prerender in their suggestions.

**Comment by thoop** [comment]
Please do let me know! Feel free to email me or even add me to that email chain if you'd like me to help out. todd@prerender.io

I'll close this now but please feel free to reopen the issue if needed.
