### ISSUE TITLE
Issue whitelising root of my site

### ISSUE THREAD

**Issue by bazooze** [prerender/prerender-node#131]
Hi, I'm attempting to whitelist the root of my site only (all other pages should not go through pre-render).  It doesn't seem to be working as expected.

The url of my root page: "mywebsite.com/".

My Express code:
app.use(require('prerender-node')
		.set('prerenderToken', process.env.PRERENDER_TOKEN)
		.whitelisted('^/$'));

I have tested by navigating to my site using "mywebsite.com/?_escaped_fragment_=" and can see that the html version is NOT returned.

This works (removing $ from regex), but means all pages are pre-rendered:
	.whitelisted('^/'));

I did look at the source for this page, but couldn't grok what was happening with the whitelist function.

Any help greatly appreciated!

**Comment by thoop** [comment]
Hi there! Hmmm, if crawlers are accessing `?_escaped_fragment_=` URLs then you might have that parameter on the end of the URL, causing that regex to not match it? If so, the incoming URL would be `/?_escaped_fragment_=`

**Comment by bazooze** [comment]
Ah ok - that makes sense.

Another thing I tried was spoofing the Googlebot user agent via curl:
curl -A "Googlebot/2.1 (+http://www.google.com/bot.html)" https://mywebsite.com/

I don't see this in the crawler stats though?  Can you recommend an easy way to test what googlebot see's for my site?  This will help me to get the regex correct for my whitelist.

Thanks!

**Comment by thoop** [comment]
The Googlebot user agent isn't being checked by default because they currently support crawling using the escaped fragment crawling protocol. Meaning, if you have `<meta name="fragment" content="!">` in the `<head>` of your pages, the will access the `?_escaped_fragment_=` URL. So for your homepage, Google would request `https://mywebsite.com/?_escaped_fragment_=`

**Comment by bazooze** [comment]
Thanks Todd - that explains things!

**Comment by derwaldgeist** [comment]
I'm struggling with this, too.

`'^/sign-in'` works as a white-list, while
`'/sign-in?_escaped_fragment_='` doesn't.

So I assume the escape-fragment part should not be part of the regex.

But if I try to setup a whitelist for the root path, it fails.
`'/?_escaped_fragment_='` matches all routes
`'^/?_escaped_fragment_='` matches no route, not even the root path
`'^/$' doesn't work either

What is the correct setup for matching the root (and only the root)?
