### ISSUE TITLE
Adding custom user agents

### ISSUE THREAD

**Issue by rivertam** [prerender/prerender-node#132]
I'd love to be able to add extra user agents so I can use prerender more! I'm hosting my application behind CloudFront, and I'd rather not forward user agents through CloudFront for performance reasons. I'd rather just prerender everything that comes through CloudFront! But I recognize this is not expected behavior for everyone. So ideally I'd be able to add CloudFront's user agent to the middleware custom.

**Comment by rivertam** [comment]
Oh, I think I can do this by saying

    var prerender = require('prerender-node')
    var currentUserAgents = prerender.crawlerUserAgents;
    prerender.set('crawlerUserAgents', currentUserAgents.concat([/* user agents go here */]));
    // continue as normal

**Comment by thoop** [comment]
You don't want to serve prerendered pages to your users and prerendering everything with the cloudfront user agent would serve prerendered pages to your users, right?

**Comment by rivertam** [comment]
Yeah that just occurred to me. Are prerendered pages unusable?

**Comment by rivertam** [comment]
Oh it actually caused a circular request -- when prerender requested the page, CloudFront requested the page, which caused a request to prerender...

Any ideas on how I can implement prerender.io behind CloudFront without forwarding User-Agent strings? @thoop (I understand if not)

**Comment by thoop** [comment]
You should be able to handle Google, Bing, Yandex, and a few others with just the `_escaped_fragment_` URLs. If you are using CloudFront, you might want to take a look at Lambda@Edge https://aws.amazon.com/blogs/aws/coming-soon-lambda-at-the-edge/.

In that case, you could run the prerender-node middleware (or something similar) to proxy requests to Prerender at the CloudFront level.

**Comment by rivertam** [comment]
Thanks for the resource! Looks awesome. =)

It looks like Google doesn't use the `_escaped_fragment_` thing anymore ([source](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html)). Do you know if that method will still work?

**Comment by thoop** [comment]
Yep! Google does still crawl using the `_escaped_fragment_` crawling protocol if you have `<meta name="fragment" content="!">` in the `<head>` of your page. So that's still valid and we still suggest that you use it.

**Comment by rivertam** [comment]
I'm gonna try out the Lambda@Edge thing first because I'm a sucker for trendy tech, but glad to hear it.

**Comment by thoop** [comment]
Cool! Report back with any info on how easy/hard it is to set up!

**Comment by maulsea** [comment]
@rivertam Did you have any luck with Lamda@Edge? I'm struggling to get the access to Lamda@Edge preview. But, I am eager to find out if it will be any useful in case I get it. Let me know if possible. :)

**Comment by rivertam** [comment]
No response to a request for access. =/ Ended up not using CloudFront at all.

**Comment by maulsea** [comment]
@rivertam Same here, may I know what you ended up using? I guess I will have to move away from CloudFront too.

**Comment by rivertam** [comment]
Oh I mean we moved away from using any CDN. It wasn't helping performance enough.
