### ISSUE TITLE
How to add configuration parameters such as waitAfterLastRequest?

### ISSUE THREAD

**Issue by chrillewoodz** [prerender/prerender-node#133]
How do you add configuration parameters such as `waitAfterLastRequest` when using it like this:

    var preRenderer = require('prerender-node')

    app.use(preRenderer);

The docs only say how to configure plugins, not additional parameters.

**Comment by thoop** [comment]
That parameter that you mentioned is a prerender server parameter that cannot be modified from the prerender middleware. So that's not something you can do.

**Comment by chrillewoodz** [comment]
So you have configuration options that are non-configurable? How am I supposed to set them then? Do I need to clone the project and somehow merge your `server.js` file with our existing `server.js` file and set the parameters for the prerender server that way?
