### ISSUE TITLE
No cached page?

### ISSUE THREAD

**Issue by natashache** [prerender/prerender-node#134]
Hi,
I'm using prerender.io for a reactjs app with node/express backend. From what I gathered in the documentation, all I need to do is to 
1) npm install `prerender-node`, 
2) add `app.use(require('prerender-node').set('prerenderToken', 'mytoken'))` to my server code, 
3) add `<meta name="fragment" content="!">` to my html head.

Is that all? I ask because when I log into my prerender.io account, it keeps telling me there're 0 cached pages. And I've added the above to my deployed app for about a week now. Not sure what I'm not doing right. Appreciate any insight. Thanks!

**Comment by thoop** [comment]
That looks correct. It's possible that you have other code running before that `app.use()` call which could prevent the middleware from running on each request. Can you email us the URL where you have this installed and your application file where you are using `app.use()` with any private info removed? I'd be happy to look into it. support@prerender.io

**Comment by natashache** [comment]
Thanks @thoop. Email sent.
