### ISSUE TITLE
localhost not working

### ISSUE THREAD

**Issue by harshitwalia** [prerender/prerender-node#136]
when i try to go to http://localhost:3000/https://www.google.com
it redirects me to google.com original website

**Comment by thoop** [comment]
Can you send over what you see when you run:

`curl -I http://localhost:3000/https://www.google.com`

**Comment by harshitwalia** [comment]
I see www.google.com
This might be because i am using ubuntu 16.04 lts

**Comment by thoop** [comment]
Can you show the full output from running this command?

`curl -I http://localhost:3000/https://www.google.com`

I'd like to see all the headers being returned. I don't think it has to do with using ubuntu 16.04.
