### ISSUE TITLE
How do i test if specific pages in whitelist get prerendered correctly?

### ISSUE THREAD

**Issue by posrix** [prerender/prerender-node#137]
```
prerender.whitelisted(['/'])
prerender.set('beforeRender', (req, done) => {
    console.log('start render')
    done()
})
```
doesn't work for me

**Comment by thoop** [comment]
Which URL are you requesting to test that it's working?

**Comment by posrix** [comment]
'/', which mean index.html

**Comment by thoop** [comment]
If you are accessing '/' then it should work. If you are accessing /?_escaped_fragment_= then you might need to specify that in the whitelisted as well, like:

`prerender.whitelisted(['/', '/?_escaped_fragment_='])

**Comment by posrix** [comment]
But the 'beforeRender' hook doesn't console.log any text i expected

**Comment by thoop** [comment]
Does it work if you remove the `whitelisted` call and use the middleware on all URLs?

**Comment by posrix** [comment]
No, it doesn't.

Here's what does output in console.

```
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./index.js`
[HPM] Proxy created: /  ->  http://homev5.test.nodevops.cn
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /  ->  http://feature-1249.game_security_home.test.nodevops.cn
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
Server started ! ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:8101
      LAN: http://192.168.199.152:8101
-----------------------------------
Press CTRL-C to stop

[HPM] GET /api/V4/site.today.report.allplat -> http://homev5.test.nodevops.cn
[HPM] GET /api//sso/V4/attach?callback=jsonp_1497716189479_28088748347221837&_time=1497716189479 -> http://homev5.test.nodevops.cn
[HPM] GET /api/V4/site.friendlink -> http://homev5.test.nodevops.cn
[HPM] GET /api/sso/V4/getUserInfo -> http://homev5.test.nodevops.cn
```

**Comment by thoop** [comment]
From the log you sent over, it looks like you are just serving /api/ endpoints from your server. Is that correct? Does this server actually serve your index.html (or whichever page bootstraps your javascript) to the crawlers?

**Comment by posrix** [comment]
Nope, the /api stuff is just proxy using `http-proxy-middleware`. I use `express.Router()`  to dynamically serve the pages.

**Comment by thoop** [comment]
Sorry for the delay! Feel free to reopen if you are still having issues.
