### ISSUE TITLE
Browser sync compatibility ?

### ISSUE THREAD

**Issue by clemator** [prerender/prerender-node#139]
Hey there, I would like to try prerender for Node but I am using browser-sync instead of Express.
After several attempts, it does not seem possible. Can you confirm this please ?
Thank you !

**Comment by clemator** [comment]
In the end, prerender is not a good solution for my project. But I made it work by adding the prerender on the browser sync middleware solution.

**Comment by thoop** [comment]
Sorry for the delay! You are correct prerender-node will only work with Connect compatible middleware options. Let us know if you have any questions about that.
