### ISSUE TITLE
Google Bot received 504's when crawling, but "Fetch As Google" using identical URL returns 200

### ISSUE THREAD

**Issue by matt-iakhno** [prerender/prerender-node#140]
Hi Prerender-node team,

I am having an issue with Google Bot accessing my site and as a result very little content (<10% of all pages) is getting indexed. I have set up a prerender server on a micro instance in EC2, with caching to an S3 bucket enabled (this all works fine), and prerender-node middleware on the site itself. 

After waiting a few days I noticed that I was having 100s of crawl errors in search console, so I checked them out and it seems Google Bot is getting a 504 back whenever it tries to access almost any part of the site. The weird thing is, however, if I "Fetch As Google" on any of the URLs Google Bot tried to crawl the prerender pipeline works beautifully and I am able to see the markup.

Here is an example:

URL: https://www.nosey.com/channel/american-gladiators-parent/video/587950529fcf70190eafa7dd

Search console screenshot showing 504 error when Google Bot tried to crawl this page: http://i.imgur.com/0WjlFRv.png

The exact URL that Google was hitting when it got 504 (from the screenshot): https://www.nosey.com/channel/american-gladiators-parent/video/587950529fcf70190eafa7dd?_escaped_fragment_=

Fetch As Google for the above URL: http://i.imgur.com/fOf8p1D.png

Fetch As Google rendered results (shows that all data from all AJAX came in): http://i.imgur.com/yNILgpS.png

As you can see, both Prerender server and prerender-node seem to be working. Prerendered markup is getting stored in the S3 bucket and is being served back to the Google bot correctly, but ONLY with "Fetch As Google".

Does anyone have any ideas on how I might be able to fix the 504s?

**Comment by thoop** [comment]
Responded to your email so I'll close this issue.

**Comment by ferchudzik** [comment]
we are facing this problem. how was this solved?

**Comment by matt-iakhno** [comment]
Hi @ferchudzik 

I did the following so far and overnight the # of pages indexed increased and the # of errors went down significantly. I'm still getting 504s on some pages but it has improved significantly:

-moved the Prerender service to a larger instance (XS -> M in AWS EC2)
-set softIterations to 5* - this is on the Prerender service itself, not the middleware. The documentation at https://github.com/prerender/prerender explains all the different options 
-set iterations to 50*

*both at the recommendation of a Prerender developer.

**Comment by ferchudzik** [comment]
Thanks for the response @matt-iakhno , I will apply these steps and monitor the results for a few days as well. Any news will inform you.

**Comment by matt-iakhno** [comment]
Just following up for anyone who may run into this problem in the future: the steps outlined above have made almost all the server errors disappear. There is still an occasional 504 but the error counts have gone down to the low 10s from 1000+.

**Comment by redka** [comment]
hi @thoop! I also have this problem. Please send me solve the problem by mail.
Now, I have options:
Environment='CACHE_MAXSIZE=1000'
Environment='CACHE_TTL=600'
Environment='PRERENDER_NUM_ITERATIONS=50'
Thanks!

**Comment by thoop** [comment]
@redka Are you running your own Prerender server? Which version of Prerender are you using?

**Comment by redka** [comment]
@thoop Friday updated to last.
https://developers.google.com/webmasters/ajax-crawling/docs/getting-started
**The syntax described by this page is no longer required, and will not be supported after the summer of 2018.** !!!
Now I think, prerender doesn't work for Googlebot!!!

**Comment by thoop** [comment]
Google has announced that the will stop requesting escaped fragment URLs in Q2 of 2018 and will render the javascript themselves:

https://webmasters.googleblog.com/2017/12/rendering-ajax-crawling-pages.html

I have to assume that means Google will render pages 100% correctly (otherwise they wouldn't turn off the escaped fragment support) so you shouldn't run into any issues there. Prerender will still be needed for Bing, Facebook, Twitter, Yandex, Baidu, and all other crawlers since Google will be the only crawler executing any meaningful amount of javascript.
