### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by sakshigargit** [prerender/prerender-node#144]
Hi Everyone,

I am getting the dependency issue while integrating it in my Vue.js project.

Every time when I integrate it I got fs net and tls dependency issue.

Please help me I have to integrate it in my Vuejs project.

**Comment by sakshigargit** [comment]
Please help me out in this I am using it with Vuejs not Express.

**Comment by thoop** [comment]
Let's keep this discussion in this thread:
https://github.com/prerender/prerender-node/issues/143
