### ISSUE TITLE
Koa support [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [prerender/prerender-node#145]
Would it be possible to add koa support in official current lib?

It seems like https://github.com/RisingStack/koa-prerender supports only the external 3rd party service (https://github.com/prerender/prerender-node/issues/35)

**Comment by thoop** [comment]
I'm not sure what you mean by koa-prerender only supporting external 3rd party service. Can you expand on what you mean by that? It looks like koa-prerender lets you change the URL for your prerender service:

https://github.com/RisingStack/koa-prerender/blob/master/index.js#L124

**Comment by thoop** [comment]
Feel free to reopen if you are still having issues here.
