### ISSUE TITLE
Is it possible to serve the gzipped version straight to end users?

### ISSUE THREAD

**Issue by oscarni** [prerender/prerender-node#147]
It looks like this middleware always unzip the gzipped files before serving them to the user.
https://github.com/prerender/prerender-node/blob/master/index.js#L196

Is there a specific reason for always unzipping?
I would like to serve gzip to my visitors/bots if they allow that through their headers.

Am I missing some setting to do this? Otherwise I'm happy to give it a shot and make a PR to solve it.

**Comment by thoop** [comment]
That's unzipping the response so that you can have access to the unzipped content in the `afterRenderFn` function. If you have another middleware set up for compression, it should re-gzip everything before sending the response. So I don't think it's necessary to keep the gzip encoding.

**Comment by oscarni** [comment]
Alright, I'll check some compression middleware. Just felt so unnecessary to do it again when it already was gzipped.
