### ISSUE TITLE
Blank page when trying to cache

### ISSUE THREAD

**Issue by rubenjimenez** [prerender/prerender-node#149]
Hi,

Recently I updated to the last available version of prerender server. I noticed it had replaced phantomjs for Chrome and it works properly. Previously I was using S3 as cache but in this version it is not available. No problem, I decided to implement the cache layer in my webserver through prerender-node and using Redis.

The main problem is that it's not working and I don't know why. When I'm trying to retrieve the HTML version of a given page, I just receive a blank page. No errors in Node or browser, just a blank page.

The Node console prints the "BEFORE RENDER" but not the "AFTER RENDER". Besides, the request is not displayed in Prerender server. If I comment the beforeRender and afterRender events, everything works right.

This is the code I'm using in my express.js:

```
  prerender = require('prerender-node'),
  redis = require('redis'),
  client = redis.createClient(),
  cacheableStatusCodes = {200: true, 302: true, 404: true};

  app.use(prerender.set('prerenderServiceUrl', 'http://localhost:7331'));

  prerender.set('beforeRender', function(req, done) {
    client.hmget(req.url, 'body', 'status', function (err, fields) {

      console.log('BEFORE RENDER');
      console.log('Url: ' + req.url);
      
      if (err)
        return done(err);

      done(err, {body: fields[0], status: fields[1]});

    });
  }).set('afterRender', function(err, req, prerender_res) {

    console.log('AFTER RENDER');
    console.log('Url: ' + req.url);

    if ( err ) return console.log(err);

    // Don't cache responses that might be temporary like 500 or 504.
    if (cacheableStatusCodes[prerender_res.statusCode])
      client.hmset(req.url, 'body', prerender_res.body, 'status', prerender_res.statusCode);

  });
```

Am I missing something?

Thanks!

**Comment by rubenjimenez** [comment]
Ok, I think I've found the issue.

Initially, there're no rendered pages in cache, so fields[0] and fields[1] from Redis are null, so we have the next obj:

```
{ body: null, status: null }
```

which is passed to the beforeRenderFn function. This function doesn't seem to validate in a proper way this kind of object:

```
    if (!err && cachedRender) {
      if (typeof cachedRender == 'string') {
        res.writeHead(200, {
          "Content-Type": "text/html"
        });
        return res.end(cachedRender);
      } else if (typeof cachedRender == 'object') {
        res.writeHead(cachedRender.status || 200, {
          "Content-Type": "text/html"
        });
        return res.end(cachedRender.body || '');
      }
    }
```

The function returns an empty body and therefore browser gets a blank page because the object exists but it haven't got any content.

I solved the issue checking the fields array content before to pass it to the done() callback. If it is empty, I just pass null.

```
done(err, null);
```

and finally it works.

Maybe the example in the README should be fixed for avoiding any misunderstanding.

**Comment by thoop** [comment]
Ah, great point and sorry that's not documented! We should probably change the code to check for `cachedRender.body` to make sure that's always passed in. I don't think the empty string response there is useful in any way...

**Comment by rubenjimenez** [comment]
No problem @thoop, thanks for such a great tool.
