### ISSUE TITLE
Consider dropping support for EOL node versions

### ISSUE THREAD

**Issue by michaeljoseph** [prerender/prerender-node#152]
This project's only dependency, dropped support for node versions < 4 quite some time ago (https://github.com/request/request/blob/master/CHANGELOG.md#v2770-20161103).

Would you consider cutting a major release that followed suit?

**Comment by thoop** [comment]
Yeah I think we could do that with a correct version bump on our end to not break anyone using the old version still. We'll look into doing this soon.

**Comment by michaeljoseph** [comment]
Cool! Lemme know if there's anything I can do to help...

**Comment by thoop** [comment]
Thanks! Sorry. Been super busy lately. I'll merge this soon...just want to do some manual testing before I do.

**Comment by thoop** [comment]
Merged and pushed in 3.0.0.

Thanks!
