### ISSUE TITLE
I am not using _escaped_fragment_ , wondering if prerender support Google Bot

### ISSUE THREAD

**Issue by benpptung** [prerender/prerender-node#155]
Just found Google Bot fetching one page of our website,
but prerender didn't generate any cache.

I see the following comments.
// googlebot, yahoo, and bingbot are not in this list because
// we support _escaped_fragment_ and want to ensure people aren't
// penalized for cloaking.

Wondering if Prerender support Google Bot?

**Comment by thoop** [comment]
Yes, Prerender supports Googlebot. If you have `<meta name="fragment" content="!">` in the `<head>` of your page, Googlebot will request the `_escaped_fragment_` URLs which the middleware checks for.

In Q2 of 2018, Google will stop requesting the escaped fragment URLs and start executing javascript on their own. If they cannot render your javascript at that point in time, you might want to think about checking Googlebot by their user agent.

https://webmasters.googleblog.com/2017/12/rendering-ajax-crawling-pages.html

**Comment by benpptung** [comment]
Hi thoop,

Thank you for your reply.
I just realized what _escaped_fragment_ is and Prerender.io save my life!!!

Thank you for this great API. Our website has been relaunched 2 months, eventually, I see Google to index our images today!! Thank you :)

**Comment by thoop** [comment]
Great! Glad we could help 😄
