### ISSUE TITLE
Cloudflare + Heroku + Node

### ISSUE THREAD

**Issue by t2** [prerender/prerender-node#156]
We are currently experiencing a very similar situation as stated here https://github.com/prerender/prerender-node/issues/92. We have a ReactJS application behind a node server running on Heroku with Cloudflare as the DNS provider. We are using Cloudflare's Flexible SSL. When using the https://www.website.com/user/1?_escaped_fragment_= we get 301 redirected back to the root route.

Any ideas? What information can I provide to help debug? We are new to using prerender.

**Comment by thoop** [comment]
From your other question on #92, you would use `.set('protocol', 'https')` like:
```
app.use(require('prerender-node').set('prerenderToken', 'YOUR_TOKEN').set('protocol', 'https'));
```

That will force the prerender-node middleware to send all requests to Prerender.io as an https URL instead of http to solve that redirect issue.

Let me know if that doesn't fix your issue!

**Comment by t2** [comment]
@thoop Unfortunately that didn't work.

**Comment by t2** [comment]
@thoop Actually, it was my fault. I was doing 

```
app
    .use(
      require('prerender-node').set('prerenderToken', 'token')
    )
    .set('protocol', 'https');
```
and should have been doing 

```
app
    .use(
      require('prerender-node')
          .set('protocol', 'https')
          .set('prerenderToken', 'token')
    )
```

**Comment by thoop** [comment]
Glad that worked! 😄
