### ISSUE TITLE
googlebot escape_fragment

### ISSUE THREAD

**Issue by hanstf** [prerender/prerender-node#158]
I am currently using the latest prerender node which is 3.1.1 with prerender hosted service

When I try to use the "Fetch as Google" tools inside google webmasters. It seems like it is not getting the result from prerender as when I go to prerender website it is not showing inside the "Crawled page" section.

Is "Fetch as Google" does not use the "__escape_fragment__" ?

Sorry if I am in the wrong room

**Comment by thoop** [comment]
Hi there! Unfortunately, Fetch as Google has never followed the escaped fragment crawling protocol...which is pretty weird. The real Googlebot will currently follow the escaped fragment crawling protocol though.

So when using Fetch as Google, you will want to manually enter the `?_escaped_fragment_=` on the URL to make sure they receive a prerendered page. And as long as you have `<meta name="fragment" content="!">` in the `<head>` of your page, the real Googlebot will see that and automatically request the `?_escaped_fragment_=` URLs.

Let me know if you have any questions about that.
