### ISSUE TITLE
google not appending the ?_escaped_fragment_=  when indexing?

### ISSUE THREAD

**Issue by gregorleban** [prerender/prerender-node#159]
Hi,

I'm sorry for posting this as an issue here but I hope that you can shed some light on my issue. 

I'm using prerender to index my website that has dynamic content. Until recently (like a month or two ago) I was receiving requests from google with the ?_escaped_fragment_= part which allowed my node application to detect these requests and process them accordingly. 

Recently I've been getting a lot of requests from the googlebot that don't have this part added in the url and my node.js handler is not able to detect these requests as coming from a googlebot so it's not handling the requests and this is very bad for indexing my site.

Do you have any idea what could be the reason for this issue?

Thank you in advance for any help!

Best,
Gregor

**Comment by thoop** [comment]
We haven't seen Google stop crawling `?_escaped_fragment_=` URLs yet on our end, but we have been hearing from some customers that Google is executing the javascript on the first request to a URL even though they will later request the `?_escaped_fragment_=` URL too. Do you still have `<meta name="fragment" content="!">` in the `<head>` of your website?

Google announced in May that they've relaxed the Cloaking check and you can serve a prerendered page directly to Googlebot by checking the user agent. That way, you can add `googlebot`, `bingbot`, and `yandex` to the list of user agents being checked by the middleware and then remove the `<meta name="fragment" content="!">` tag from your HTML.

More info on that can be found here: https://www.seroundtable.com/google-dynamic-rendering-25736.html

**Comment by YannDanthu** [comment]
Hi, 
same problem here. Since june 20th all of our URLs are not indexed anymore by Google :(
It seems that they do not use the `?_escaped_fragment_=` anymore but migrated to a Mobile First index process.

**Comment by YannDanthu** [comment]
I confirm that the `user-agent` of google has changed to `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)` :( meaning that prerender is never requested

**Comment by thoop** [comment]
@YannDanthu We are still seeing `?_escaped_fragment_=` for our customers. If they aren't requesting `?_escaped_fragment_=` URLs, you can serve a prerendered page directly to Googlebot by checking the user agent. You can add googlebot, bingbot, and yandex to the list of user agents being checked by the middleware and then remove the <meta name="fragment" content="!"> tag from your HTML.

If you are using `prerender-node`, you would do it like:
```
var prerender = require('prerender-node').set('prerenderToken', 'YOUR_TOKEN');
prerender.crawlerUserAgents.push('googlebot');
prerender.crawlerUserAgents.push('bingbot');
prerender.crawlerUserAgents.push('yandex');

app.use(prerender);
```
