### ISSUE TITLE
Doesn't work for Fetch As Google

### ISSUE THREAD

**Issue by evasiliskin** [prerender/prerender-node#163]
Hello.
The middleware does not work for "Fetch As Google" if I use google webTools . The option with the name "crawlerUserAgents" does not contains "Google Web Preview".
See more for "Fetch As Google" on this article
https://trevorfox.com/2018/03/fetch-as-google-experiment/

Thank you.

**Comment by anhlevfx** [comment]
Hi @evasiliskin I'm using prerender.io for my client website (Angular 5 and NodeJS), Fetch As Google not work for me too, it rendered a blank page (or just a simple part of my page - a plugin chat). I contacted with the author few months ago and he confirmed that bots of Fetch Google will work not right with plugin, but real google crawlers work well.

**Comment by thoop** [comment]
@evasiliskin Fetch as Google works for us on https://prerender.io

![image](https://user-images.githubusercontent.com/1259374/44604377-56a99280-a7ab-11e8-870a-77eb46e6eefe.png)

Are you seeing an incorrect page on the left screenshot or right screenshot from Fetch as Google? Feel free to send over your URL if you want us to test if it's working correctly. support@prerender.io

**Comment by thoop** [comment]
Ah ok. If you update to the latest prerender-node, we are checking Googlebot by their user agent by default so that should work fine with our latest prerender-node. Glad you got it working!
