### ISSUE TITLE
WhatsApp/Telegram/Slack support for prerendered pages not working

### ISSUE THREAD

**Issue by rubenjimenez** [prerender/prerender-node#168]
Hi,

A client has requested that If we can do something to improve the link previews in WhatsApp, Telegram, Slack and so on.

We're using prerender-node 2.7.4 and prerender server 5.2.0. According to what we've been checking, prerender-node added the WhatsApp user agent in 2.2.0 version.

Therefore, previews should work properly in WhatsApp out-the-box but they don't. Any suggestion?

Thanks!

**Edit**
Updated pretender-node to 3.2.1 and prerender server to 5.4.5 but it still doesn't serve the dynamic generated preview to WhatsApp.

**Comment by thoop** [comment]
Can you send us an email at support@prerender.io with your website and how you've set up the Prerender.io middleware so we can run some tests? From what you sent, it sounds like it should be working properly.

**Comment by paulincai** [comment]
@thoop I encounter a similar situation where WhatsApp OSX App (WhatsApp/0)generates a preview nice and quick (8-10ms) but WhatsApp mobile (IOS) (WhatsApp/2) and WhatsApp Web (WhatsApp/2) does the crawling but now preview is displayed. The url is tested with FB for og: compliancy. This is the log from Prerender server. It looks like only WhatsApp/0 user agent is returning content ... or so...

```
554.170.31.203 - - [20/Mar/2019:22:07:41 +0000] "GET /https://www.activitree.com/activities/culture/archaeological_site HTTP/1.1" 200 36042 "-" "WhatsApp/0.3.2386 N"                                
54.170.31.203 - - [20/Mar/2019:22:08:02 +0000] "GET /https://www.activitree.com/activities/culture/archaeological_site HTTP/1.1" 200 36042 "-" "WhatsApp/2.19.31 i"   
```

**Comment by rubenjimenez** [comment]
I'll post here the explanation @thoop gaves me when we were discussing this topic by email:

> Hi Ruben,
>
> I'm not sure if WhatsApp support the ?_escaped_fragment_= URLs so if you share on WhatsApp, do they always show the info for your homepage? If so, you will need to remove the #! from your URLs in > order to get things working. Google and Bing are also not requesting the ?_escaped_fragment_= URLs anymore so we've added their user agents to be checked by the middleware as well.

Indeed, our project was working using the !# in the URLs. Now, we're migrating the project to a new MEAN scaffolding with push state URLs.

More interesting things @thoop explained:

> Facebook and Twitter seem to still access ?_escaped_fragment_= URLs but you will want to move to html5 push state URLs if possible since everyone seems to be moving away from that.
