### ISSUE TITLE
Bots using #! instead of "?_escaped_fragment_=" are returned home page instead of correct page

### ISSUE THREAD

**Issue by lesuto** [prerender/prerender-node#175]
When running a bot in google inspect element it returns the home page instead of the proper page when using #! instead of ?escaped_fragment=. There seems to be an issue with directing to the proper page. 

homeplanmarketplace.com/#!/marketplace/home-plan?plan_id=001-3223 => home page
homeplanmarketplace.com/?_escaped_fragment_=/marketplace/home-plan?plan_id=001-3223 => Correct Plan Details Page

**Comment by kedrovski** [comment]
Hi @lesuto ! I found the same problem, when I use user agent in curl it return home page, when use escaped_fragmen it works fine. How you solve it?
