### ISSUE TITLE
AngularJS Node. Prerender appending multiple queries to URL and caching them

### ISSUE THREAD

**Issue by lesuto** [prerender/prerender-node#176]
I am seeing this happen quite often, where every query simply gets tacked onto the previous query. This is resulting in 1000's of dirty cached page links.

How can I prevent this from happening? It's almost as if it is running into collisions with multiple users accessing the same page with different parameters. 

https://www.homeplanmarketplace.com/?HPMhost_id%3ALESUTO%2Cplan_id%3A001-4055!HPM=&host_id=LESUTO&host_id=LESUTO&plan_id=009-3613&plan_id=013-4004#!/marketplace

**Comment by thoop** [comment]
It looks like a crawler is accessing that URL. We don't modify the URLs being sent to us to add any query parameters. Feel free to send us an email at support@prerender.io and we'd be happy to help you ignore those query parameters if they don't affect the rendering of your pages.
