### ISSUE TITLE
Bump up request@2.87.0 package due to a severe graded vulnerability with extend@3.0.1

### ISSUE THREAD

**Issue by elmargasimov** [prerender/prerender-node#178]
I am using Snyk, which has currently found a vulnerability with the extend package (used by request). If you bump up request to the latest version, it should solve this. Here are the details of the vulnerability:

Prototype Pollution
Vulnerable module: extend
Introduced through: prerender-node@3.2.2  and others

**Comment by thoop** [comment]
Thanks for the heads up. We'll update that dependency and bump the version soon.

**Comment by elmargasimov** [comment]
Perfect let me know, so I can close the issue.

**Comment by thoop** [comment]
Request has now been updated to `v2.88.0` in `v3.2.4` of `prerender-node`. We had a `^` in our previous package.json but it's now been upgraded and we also now have a package-lock.json with `v2.88.0`.

**Comment by elmargasimov** [comment]
Perfect. I will close this issue.
