### ISSUE TITLE
Can we customize the waiting time for prerender?

### ISSUE THREAD

**Issue by arangelp** [prerender/prerender-node#179]
We would like to increase the time that prerender waits until the page is render.
Is there any option to do it?

**Comment by thoop** [comment]
Sorry for the delay here. You are currently not able to modify the prerender-node middleware to affect the time that the Prerender server waits for the page to render.

I would suggest using our `window.prerenderReady` flag to tell the Prerender browser to wait longer: https://prerender.io/documentation/best-practices

**Comment by craftedsystems** [comment]
The link to the documentation is outdated. Use this one instead:
[Docs: Best Practices (prerenderReady)](https://docs.prerender.io/docs/11-best-practices?highlight=prerenderReady)
