### ISSUE TITLE
Not working under Meteor 2.5.3

### ISSUE THREAD

**Issue by bmustata** [prerender/prerender-node#221]
The current packages is not working under Meteor 2.5.3

```
➜  meteor --version                 
Meteor 2.5.3
➜  meteor node -v                   
v14.18.2
➜  meteor npm -v                    
6.14.15

```

Code
```
const prerender = require('prerender-node')
PRERENDER_TOKEN = '' // from https://prerender.io/install-token

Meteor.startup(() => {
    if (PRERENDER_TOKEN) {
        prerender.set('prerenderToken', PRERENDER_TOKEN)
        WebApp.connectHandlers.use(prerender)
    } else console.error('Init PreRender... failed')
})
```

Error

```
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```

Current fix is to revert to the previous version of the package

```
meteor npm i prerender-node@3.3.0
```

**Comment by bmustata** [comment]
Tested with meteor 2.5.x and node 14.18.x empty app and it's working fine.

**Comment by Russell-Pollari** [comment]
I'm getting the same error. Any insight into the cause? 

My version:
➜  meteor --version                 
Meteor 2.10.0
➜  meteor node -v                   
v14.21.2
➜  meteor npm -v                    
6.14.17

**Comment by bmustata** [comment]
It's not Meteor or node.js it was a third-party library doing some overwrites.

**Comment by Russell-Pollari** [comment]
@bmustata thanks! Do you recall which library?

**Comment by Russell-Pollari** [comment]
Ok did some digging. Turns out a package called `https-proxy-agent`, which was a dependency of `web-push` was overwriting the `https` package

Upgrading `web-push` to the latest version seems to have fixed it for me
