### ISSUE TITLE
SSLv3

### ISSUE THREAD

**Issue by jaredbonobos** [prerender/prerender-node#50]
I turned off SSLv3 yesterday. This caused the prerender to break. When I turned SSLv3 back on, Prerender came back up. My assumption is the prerender.io code relies on SSLv3 for https requests.

Any fix/help would be appreciated. Thank you

**Comment by homeyer** [comment]
Closing. @jaredbonobos, feel free to re-open, but we'll need more details on how you have SSL set up to investigate further.
