### ISSUE TITLE
Does PreRender Work for SEO with Dynamic Express Routes?

### ISSUE THREAD

**Issue by 1manStartup** [prerender/prerender-node#57]
Hello I wanted to know if PreRender also works for SEO indexing of dynamic express routes?

For example, In my Express Single Page App written in Backbone (mysite.com), I understand that PreRender allows me to make mysite.com/ and other static routes like mysite.com/about or mysite.com/contact SEO ready and thus indexed/searchable by Google.

But in the case of my app. Each user has their own public profile, example: mysite.com/user/:UserID in which :UserID could be one of thousands of users in my database (think Twitter or Facebook). 

A scenario would be someone searching on Google for 'Obama' and one of the search results would be mysite.com/user/Obama. Or how when I type 'prerender-node' on Google search it gives me the this link (https://github.com/prerender/prerender-node) for Github's database.

Does PreRender-Node support this functionality? And if so how to Implement? Thanks.

**Comment by thoop** [comment]
Yes, Prerender supports that functionality out of the box. Once you install the middleware, it will check each request to see if the request was made by a crawler.

If the request was made by a crawler, it will proxy the URL to Prerender.io where we will look it up in the cache or make a request to your site for that exact URL and cache the result.

So you just have to install the middleware normally and everything will work as expected.

Feel free to email me if you have any questions. todd@prerender.io
