### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by dottodot** [prerender/prerender-node#60]
I'm trying to get this running on my site and prerender.getPrerenderedPageResponse seems to be receiving the req ok but I'm just getting a blank when adding ?_escaped_fragment_= to my url.

My site was previously using the .htaccess implementation and worked fine.

**Comment by thoop** [comment]
Can you send me the URL you're testing? Thanks! todd@prerender.io

**Comment by dottodot** [comment]
http://www.boxxerworld.com/?_escaped_fragment_=

**Comment by thoop** [comment]
Is this still a problem after the fix in your other issue?

**Comment by dottodot** [comment]
No it was all related
