### ISSUE TITLE
Not rendering based on user agent, only ?_escaped_fragment_=

### ISSUE THREAD

**Issue by sabrehagen** [prerender/prerender-node#64]
I've been using prerender-node and only ever tested that it is working by appending `?_escaped_fragment_=` to the end of any url. It renders successfully using the query string, however I just tried setting my user agent to googlebot and a variety of others and prerender didn't render the page - I received the unrendered original.

I'm just using `router.use(require('prerender-node'))``.

Is anybody else experiencing this? Am I missing some configuration? Reading the other issues suggests this was how you identified bots in the first place and the query string was an enhancement - now it seems not to be working. Any ideas?

**Comment by thoop** [comment]
Which user agents did you try? Using the Googlebot user agent should _not_ cause a prerendered page because that would be cloaking. We use the `_escaped_fragment_` protocol for Googlebot.

Here's the list of user agents we check for: https://github.com/prerender/prerender-node/blob/master/index.js#L37

Let me know if there are any user agents that we should add.

**Comment by sabrehagen** [comment]
Using my Chrome user-agent changing extension I tried Googlebot, Yahoo, and BingBot. That would explain why all three didn't work. Sorry to trouble you, and good to know you're looking out for us with cloaking.

I guess I would have to ask, is it guaranteed that Googlebot will always use _escaped_fragment_ when querying? We had prerender in production for about a month and didn't see much happen to our indexes in google. For example, we still had angular curleys in our meta description.

**Comment by thoop** [comment]
If you are using html5 push state (or any URL without the #!), you need to have `<meta name="fragment" content="!">` in the `<head>` of the page. That is the signal to Google and Bing that you want them to use the `_escaped_fragment_` when querying. They will then see that meta tag and re-request the page with the escaped fragment URL, which will then be matched by the middleware and proxied to our service.

So make sure you have that meta tag in your pages and then they should be requesting the escaped fragment URL.

**Comment by sabrehagen** [comment]
Ah! That was it! I've never come across that in my reading on the internet - how odd...you've saved me. Thank you.

I was just reading the code to see if there was a way to add our own bot user agents to the crawlerUserAgents array at runtime. Is this a planned feature?

**Comment by thoop** [comment]
It would be something like this:

```
prerender = require('prerender-node');
prerender.set('crawlerUserAgents', ['facebook', 'twitter']);
prerender.set('prerenderToken', 'YOUR_TOKEN');
app.use(prerender);
```

That will override the crawlerUserAgents list so make sure you add all of them to that list.

**Comment by sabrehagen** [comment]
Ahh, nice convenience method. Didn't realise until I looked into the code how it worked. Thanks for that!

**Comment by stephengardner** [comment]
I'd recommend `prerender.crawlerUserAgents.push('userAgent');` (use push, not set)

**Comment by thoop** [comment]
I agree! This is an old comment :) It should be:
```
var prerender = require('prerender-node');
prerender.crawlerUserAgents.push('userAgent'); //adds a user agent to the list instead of overriding
prerender.set('prerenderToken', 'YOUR_TOKEN');
app.use(prerender);
```
