### ISSUE TITLE
I made a website using yeoman , grunt ,  generator-angular,  $routeParams ... and Node.js just to build my application , how do I use the prerender and index it ?

### ISSUE THREAD

**Issue by ThiagoJem** [prerender/prerender-node#65]
Using Node.js as an application server could set like this: 
Run this on the command line:   ```$ npm install prerender-node --save```
And when you set up your express app...:  ```app.use(require('prerender-node'));```

I use Node.js only to build my application, i do not have **express**,  how could configure the **grunt** to get use **prerender** ?

**Comment by thoop** [comment]
What server do you use to actually serve requests to your application?

**Comment by ThiagoJem** [comment]
.htaccess in godaddy

**Comment by thoop** [comment]
This is our official Apache config for the .htaccess:

https://gist.github.com/thoop/8072354

**Comment by ThiagoJem** [comment]
The setting does not have Proxify ? type : RewriteRule * - [ E = Proxify : true ] .
