### ISSUE TITLE
missing brackets in documentation

### ISSUE THREAD

**Issue by MorrisDa** [prerender/prerender-node#66]
Please note in the examples afterRender, beforeRender and protocol you are missing a ')' bracket at the end!

```javascript
app.use(require('prerender-node').set('beforeRender', function(req, done) {
    // do whatever you need to do
    done();
}) //missin ) bracket here```

**Comment by thoop** [comment]
Oops, thanks! Feel free to send a pull request if you want. If not, no worries. Thanks for pointing that out.

**Comment by homeyer** [comment]
Looks like the docs are up to date now, resolving.
