### ISSUE TITLE
add Tumblr crawler

### ISSUE THREAD

**Issue by graywithanA** [prerender/prerender-node#70]
Until recently Tumblr's crawler didn't have a user agent identifying it as such. I contacted them about this (see [this issue] (https://github.com/prerender/prerender/issues/181) for more detail) and it appears they are now identifying their crawler with this user agent: "Tumblr/14.0.835.186".

I'm not sure if this is a common enough crawler to add to the list but I thought I'd bring it up.

**Comment by thoop** [comment]
Awesome! We'll definitely add it. Do they have any ability to test their crawler and what it sees?

**Comment by graywithanA** [comment]
Not that I'm aware of.  I've created a new ticket with them about another issue and plan on asking that very question so I'll let you know.

**Comment by graywithanA** [comment]
Finally heard back and they do not have any sort of preview or tester for their crawler.

**Comment by thoop** [comment]
Thanks so much for doing that! I'll add that user agent soon and push it out.

**Comment by graywithanA** [comment]
I should let you know that we there was a short period where Tumblr was not getting a prerendered version of the site despite having their crawler's user agent added to the list.  I haven't been able to investigate why this may have been but I suspect that Tumblr wasn't identifying itself for those requests.  It's working again now but the next time I notice it is broken I'll check our server logs to confirm this.

**Comment by thoop** [comment]
Interesting. Thanks for the heads up. Let me see if I can get in touch with them and verify. I'll report back here if I hear anything.

**Comment by MZAWeb** [comment]
Is there any news on this @thoop ? Thanks

**Comment by thoop** [comment]
Just added it. Thanks!
