### ISSUE TITLE
afterRender response undefined

### ISSUE THREAD

**Issue by dottodot** [prerender/prerender-node#80]
Trying to get this working on sailsjs and having an issue with afterRender

```
    app.use(prerender.set('prerenderServiceUrl', 'http://myprerender.com'));
    app.use(prerender.set('beforeRender', function(req, done) {
      var fullUrl = req.protocol + '://' + req.get('host') + req.url;
      client.get(fullUrl, done);
    }));
    app.use(prerender.set('afterRender', function(err, req, res) {
      console.log(res);
      var fullUrl = req.protocol + '://' + req.get('host') + req.url;
      client.set(fullUrl, res.body)
    }));
``` 
but the afterRender response is undefined.

**Comment by thoop** [comment]
Sorry about that! Fixed and added some tests. Can you check with v2.0.2 of prerender-node?

**Comment by dottodot** [comment]
OK that's fixed the undefined issue but ```res.body``` is empty. Any ideas why that would be?

**Comment by thoop** [comment]
res.body is not empty on mine. Are you sure you're getting a correct response back from whatever server you are accessing? what is that status code on the response? Are there any errors or anything?

**Comment by dottodot** [comment]
OK, so I believe it's because I'm getting a 504 because I was on localhost but I was also see the same problem on my live server due to the url being http://127.0.0.1 as you may have seen on my post else where. There you suggested using ```prerender.set('host', '127.0.0.1')``` but that doesn't seem to do anything so I realised maybe need to change that to my domain

so my full code is

```
    app.use(prerender.set('host', 'stickyblood.co.uk').set('prerenderServiceUrl', 'http://myprerender.com'));
    app.use(prerender.set('beforeRender', function(req, done) {
      var fullUrl = req.protocol + '://stickyblood.co.uk' + req.url;
      console.log(fullUrl)
      client.get(fullUrl, done);
    }));
    app.use(prerender.set('afterRender', function(err, req, res) {
      console.log(res.body);
      var fullUrl = req.protocol + '://stickyblood.co.uk' + req.url;
      client.set(fullUrl, res.body)
    }));
```
This is now returning a body although it's not rendering the complete page whereas when not using ?_escaped_fragment_= it renders fine i.e. http://myprerender.com/http://stickyblood.co.uk/about

So now I'm really confused as to where I'm going wrong.

**Comment by thoop** [comment]
@dottodot Are you still getting issues here? Are you using out hosted service or your local prerender instance?

**Comment by dottodot** [comment]
Yes sorry forgot to update this I had a trailing slash, so instead of 

http://stickyblood.co.uk/about?_escaped_fragment_=

I had 

http://stickyblood.co.uk/about/?_escaped_fragment_=
