### ISSUE TITLE
prerender and facebook

### ISSUE THREAD

**Issue by BrandonCopley** [prerender/prerender-node#82]
I see prerender watches for the useragents for facebookexternalhit but this user agent doesn't appear to be the user agent when using the facebook linter.

https://developers.facebook.com/tools/debug/og/object/

**Comment by BrandonCopley** [comment]
I was having issues because Facebook was showing an incorrect error. It said "type" was not a string, so I assumed it was able to retrieve my page. It was unable to retrieve the page because the SSL cert was being faked while in testing.

**Comment by thoop** [comment]
Ah, ok. Glad you got it fixed!
