### ISSUE TITLE
Prerender Not Crawling Home Page

### ISSUE THREAD

**Issue by khshah3** [prerender/prerender-node#83]
My website is

http://www.classreserve.in/

Prerender seems to be acting as middleware for all relevant pages so far. However, when a bot crawls the home page above it is not shown in the logs on my dashboard Crawl Stats. Whenever I index any other page it comes up. I have also seen the GET request in my logs being made. However, it seems like prerender doesn't intercept correctly for some reason.

https://www.google.com/#q=site:www.classreserve.in&start=0

**Comment by IsaiahJTurner** [comment]
I have this issue as well.

**Comment by thoop** [comment]
It looks like it's working correctly:

http://www.classreserve.in/?_escaped_fragment_=

And I can see the cached version that Google has from the link you sent me is rendered correctly.

**Comment by Vorror** [comment]
double confirmation that it's working: http://webcache.googleusercontent.com/search?q=cache:Z9qRHC91vZ8J:www.classreserve.in/+&cd=1&hl=en&ct=clnk&gl=us

**Comment by apitts** [comment]
@khshah3 Did you find the cause? I am having the same issue.

**Comment by apitts** [comment]
To answer my question above - the issue for me was the position of the call to prerender in my express file...it was too low. Once I moved it to the top, it worked for the homepage.

**Comment by thoop** [comment]
Great! Thanks @apitts
