### ISSUE TITLE
 Use of '&' escaped or not in URL

### ISSUE THREAD

**Issue by Desmodue** [prerender/prerender-node#85]
Hi

I am probably breaking some rule, my angular routes\URL's can sometimes contain '&' .

http://localhost/?_escaped_fragment_=/shop/BMW/3%20SERIES/83-93/E30%203%20SERIES%20320,%20323%20%26%20325/Front%20-%20Brake%20Calipers%20and%20Wheel%20cylinders

decoded
http://localhost/?_escaped_fragment_=/shop/BMW/3 SERIES/83-93/E30 3 SERIES 320, 323 &  325/Front - Brake Calipers and Wheel cylinders

This works fine for AngularJS routing, However when I pass this through prerender-node ( am using a local prerender server). The URL is reformatted, everything after '&' becomes a query parameter.

http://localhost/? 325/Front - Brake Calipers and Wheel cylinders=#!/shop/BMW/3 SERIES/83-93/E30 3 SERIES 320, 323

The page obviously does not render correctly in this case.
Is there anyway to prevent this being rewritten ? 
OR do I have to make sure my Angular routes do not have the '&' character in them ?

Regards

Gary

**Comment by thoop** [comment]
Can you look in your server logs and see exactly what URL the crawlers are accessing? That will help point us in the right direction to see how exactly the URL is encoded coming from a crawler.

**Comment by Desmodue** [comment]
This is from me testing in my browser, replacing #! with ?_escaped_fragment_=.
I am using NodeJS\ExpressJS as the back end
My angular app is served as static, so I do not see the URL when it has ?_escaped_fragment_=. IT is picked up by prerender-node and passed to the prerender server before I can log the URL.
What I do see on the prerender server is the URL written as
http://localhost/? 325/Front - Brake Calipers and Wheel cylinders=#!/shop/BMW/3 SERIES/83-93/E30 3 SERIES 320, 323

It works quite happily until it is routed through prerender-node, as you can see the URL is completely mangled.

Does that help ?

I have tried to work through the prerender-node code but it is somewhat beyond me.....
My thoughts are that the URL is being decoded before being passed through a regex to split out query params, hence why the encoded & in the URL is interpreted as a query param, even though there is no '?' in the URL to indicate a query param.... probably completely off track though.

**Comment by thoop** [comment]
The prerender-node middleware doesn't do any parsing on query params. I'll look into this and see what I can find.

**Comment by Desmodue** [comment]
You are correct, I have added some debug statements to prerender server.js and the request received from prerender-node is formatted correctl url: '/http://localhost/?_escaped_fragment_=/shop/BMW/3%20SERIES/83-93/E30%203%20SERIES%20320,%20323%20&%20325/Front%20-%20Brake%20Calipers%20and%20Wheel%20cylinders',
y.

The problem is in util.js of prerender server. The util.getUrl function. 
Guess I should post the issue there. 
Thanks

Gary
