### ISSUE TITLE
Missing Google's Structured Testing Tool in crawler user agent array

### ISSUE THREAD

**Issue by jdelibas** [prerender/prerender-node#89]
Google Structured Testing Tool is missing from the `crawlerUserAgent` array.
https://developers.google.com/structured-data/testing-tool/

The user agent
```
Mozilla/5.0 (compatible; X11; Linux x86_64; Google-StructuredDataTestingTool; +http://www.google.com/webmasters/tools/richsnippets)
```

**Comment by thoop** [comment]
The Structured Testing Tool is just a one-off and you can enter the ?_escaped_fragment_= URL into their input box for testing. Do you think this is necessary?
