### ISSUE TITLE
Missing Facebot in crawler user agent array

### ISSUE THREAD

**Issue by jdelibas** [prerender/prerender-node#90]
Facebot is missing from the `crawlerUserAgent` array.

Facebook has three different user agents.
- `facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)`
- `facebookexternalhit/1.1`

These two are covered by the `facebookexternalhit` check

And according to [docs](https://developers.facebook.com/docs/sharing/webmasters/crawler) 

```
As of May 28th, 2014 you may also see a crawler with the following user agent string:

Facebot
```

**Comment by thoop** [comment]
Have you seen `Facebot` crawling your site? We haven't seen that user agent. I'd love to see if they actually support the escaped fragment crawling protocol first. Is there a way for force them to crawl your site?

**Comment by danielparas** [comment]
@thoop you can force a crawl by using the open graph debugger:
https://developers.facebook.com/tools/debug/

**Comment by thoop** [comment]
The user agent that accesses a URL when using the open graph debugger is:
```
facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
```

**Comment by thoop** [comment]
I've still never seen this user agent. Going to close this issue until we can get some better proof that this user agent is used.
