### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by prashanthmadi** [prerender/prerender-node#91]
On your home page @ https://prerender.io/. Below are the steps to use prerender

Run this on the command line
> $ npm install prerender-node --save
And when you set up your express app...
> app.use(require('prerender-node'));

where am i specifying the external prerender server details ?

**Comment by thoop** [comment]
The external prerender server details default to our hosted service. If you want to use your own, you can pass them in the app.use call like this:
```
app.use(require('prerender-node').set('prerenderServiceUrl', 'http://yourprerenderserver.com'));
```

**Comment by thoop** [comment]
Feel free to reopen if you have any issues with that.

**Comment by prashanthmadi** [comment]
looks like prerender server is not supported in Azure web apps. As it internally uses cluster module which  isnt working on iisnode.

https://github.com/tjanczuk/iisnode/issues/391

**Comment by thoop** [comment]
Hmm sorry about that. Feel free to for prerender and remove the cluster module.
