### ISSUE TITLE
301 Moved Permanently Loop

### ISSUE THREAD

**Issue by UnifiedInc** [prerender/prerender-node#92]
I am using CloudFlare's HTTPS only feature. This may have something to do with it. I preform the following HTTPS request:
```
GET /chrome HTTP/1.1
Content-Type: application/json
Cookie: __cfduid=dd925028c8e4293ff5597f0c9bb17d38b1456509526
Host: google.com
Connection: close
```
\* Host and GET path are replaced here for security reasons.

and I receive a response filled with HTML.

```html
<html>
 <blink>YAY!</blink>
</html>
```

BUTTTT when I do a request

```
GET /chrome HTTP/1.1
User-Agent: Twitterbot/1.0
Content-Type: application/json
Cookie: __cfduid=dd925028c8e4293ff5597f0c9bb17d38b1456509526
Host: google.com
Connection: close
```

I get a response back that looks like

```
HTTP/1.1 301 Moved Permanently
Server: cloudflare-nginx
Date: Wed, 30 Dec 2015 21:07:06 GMT
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Connection: close
X-Powered-By: Express
Cf-Ray: 25d0b45dd24g23ae-IAD
Location: https://google.com/chrome
Set-Cookie: __cfduid=d9ffaae8a4c3bbdc9f04830356133c3191455509626; expires=Thu, 29-Dec-16 21:07:06 GMT; path=/; domain=.google.com; HttpOnly
Via: 1.1 vegur
```
\* Via for heroku
 ** Cf-ray and Set-Cookie for CloudFlare
 *** The 301 redirect is to the same URL??

Any ideas?

**Comment by UnifiedInc** [comment]
![screen shot 2015-12-30 at 5 43 34 pm](https://cloud.githubusercontent.com/assets/11344894/12058726/e435ae5c-af1c-11e5-942c-2036476df492.png)
Update: prerender logs reveal that the URL is not being received as HTTPS.

**Comment by UnifiedInc** [comment]
Fixed by adding `.set('protocol', 'https'));`. I believe there is an issue with the CloudeFlare logic here but since I found a solution, I'm closing the issue. Feel free to reopen if you think something should be changed on Prerender's end. I feel there should be something to make this issue easier to diagnose.

**Comment by UnifiedInc** [comment]
Fixed by adding .set('protocol', 'https'));. I believe there is an issue with the CloudeFlare logic here but since I found a solution, I'm closing the issue. Feel free to reopen if you think something should be changed on Prerender's end. I feel there should be something to make this issue easier to diagnose.

**Comment by thoop** [comment]
It looks like you were doing SSL termination at the Cloudflare level so your server was only seeing http requests and that's why the node middleware was sending an http request through. Cloudflare should have been setting the x-forwarded-proto header which we support so that shouldn't have been an issue if they were sending that. I don't think this is an issue at the prerender level unless we have other evidence.

**Comment by t2** [comment]
@ghost Where did you `set('protocol', 'https')`?

**Comment by erick2014** [comment]
The issue still happening, I had to configure my code as follows: 
  const prerender = prerenderio
    .set('prerenderToken', 'myToken')
    .set('host', 'myhost')
    .set('protocol', 'https')
  prerender.crawlerUserAgents.push('googlebot')
  prerender.crawlerUserAgents.push('bingbot')
  prerender.crawlerUserAgents.push('yandex')
  app.use(prerender)
