### ISSUE TITLE
Creating sitemap?

### ISSUE THREAD

**Issue by jsantana90** [prerender/prerender-node#95]
I've been reading on how to make an angularjs app seo friendly and ended up being recommended to use prerender.io and it seems quite interesting on how it works.

Right now, I've added prerender-node via npm to my project and am using the hashbang (#!)

My question is, how do I know for sure that it works? I've tried using `Fetch as Google` to view and render the website but I see that the `ui-view` doesn't have anything in it when google fetches it.

I've also tried using third party websites to create a sitemap which only returns the root url without adding all the other routes/states.

I've tested to see with the url instead of being `#!` using the `?_escaped_fragment_=/` and it returns the website normally so I'm guessing it's implemented correctly?

Also, I can do manually the sitemap, but what is the correct way to do it. Currently I have it like this:

```
<url>
  <loc>http://example.com/#!/results</loc>
</url>
```

**Comment by thoop** [comment]
With Fetch as Google, you need to enter the ?_escaped_fragment_= URL. Googlebot will correctly access the ?_escaped_fragment_= URL but Fetch as Google won't and you have to enter it manually there. Fetch as Google should get the correct HTML once you use the escaped fragment URL. Let me know if you need any help with that.

That is the correct way to do the sitemap. Follow the correct schema from http://www.sitemaps.org/
