### ISSUE TITLE
Support for Google App Engine SSL

### ISSUE THREAD

**Issue by 5inline** [prerender/prerender-node#98]
We came across an issue when using prerender-node with an SSL site on GAE. GAE passes a header `x-appengine-https="on"` for SSL requests. Adding:
```
  if( req.headers['x-appengine-https'] ) {
    protocol = req.headers['x-appengine-https'] === 'on' ? 'https' : 'http';
  }
```
to the `buildApiUrl` function seems to fix the issue.

**Comment by thoop** [comment]
Hmm, any idea why they use a non-standard header? X-Forwarded-Proto is pretty standard.

**Comment by thoop** [comment]
Closing without more info on that non-standard header. Feel free to reopen if you have any more info on that.
